version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python backend/back/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=back.settings