# Generated by Django 5.1.2 on 2024-10-22 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('price', models.FloatField()),
                ('organizer', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_class', models.CharField(max_length=50)),
                ('seat', models.CharField(max_length=50)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
        ),
        migrations.CreateModel(
            name='EventGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.genres')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
            options={
                'unique_together': {('event_id', 'genre_id')},
            },
        ),
        migrations.CreateModel(
            name='EventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
            options={
                'unique_together': {('event_id', 'category_id')},
            },
        ),
    ]
